TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)
    VERILOG_SOURCES = $(PWD)/../rtl/bin_2_gray.sv

TOPLEVEL := bin_2_gray
MODULE   := test_bin_2_gray

include $(shell cocotb-config --makefiles)/Makefile.sim
